---
title: "EDA"
format: html
editor: visual
---

```{r}
#| warning: FALSE
library(tidyverse)
library(reshape2)
```

## Introduction Section

## Data

```{r}
diabetesData <- read_csv("diabetes_binary_health_indicators_BRFSS2015.csv", show_col_types = FALSE)

diabetesData$Diabetes_binary <- factor(diabetesData$Diabetes_binary,
         levels = c(0,1),
         labels = c("No diabetes", "Diabetes"))

diabetesData$HighChol <- factor(diabetesData$HighChol,
         levels = c(0,1),
         labels = c("No high cholesterol", "High cholesterol"))

diabetesData$Smoker <- factor(diabetesData$Smoker,
         levels = c(0,1),
         labels = c("Never smoked at least 100 cigs", "Has smoked at least 100 cigs"))

diabetesData$PhysActivity <- factor(diabetesData$PhysActivity,
         levels = c(0,1),
         labels = c("No physical activity", "Physical activity"))

diabetesData$Sex <- factor(diabetesData$Sex,
         levels = c(0,1),
         labels = c("Female", "Male"))

diabetesData$Age <- factor(diabetesData$Age,
         levels = c(1,2,3,4,5,6,7,8,9,10,11,12,13),
         labels = c("20-24","25-29", "30-34", "35-39", "40-44", "45-49","51-54","55-59","60-64", "65-69", "70-74", "75-79", "80 or older"))

diabetesData$HvyAlcoholConsump <- factor(diabetesData$HvyAlcoholConsump,
         levels = c(0,1),
         labels = c("No", "Yes"))

diabetesData$DiffWalk <- factor(diabetesData$DiffWalk,
         levels = c(0,1),
         labels = c("No serious difficulty walking up stairs", "Serious difficulty walking stairs"))

newDiabetesData <- diabetesData |>
  select(Diabetes_binary, HighChol, BMI, Smoker, PhysActivity, HvyAlcoholConsump, Sex, Age, DiffWalk)

colSums(is.na(newDiabetesData))
```

## Summarizations

```{r}
summaryDiabetesData <- newDiabetesData |>
  filter(Diabetes_binary == "Diabetes")

mean(summaryDiabetesData$BMI)
table(summaryDiabetesData$HighChol, summaryDiabetesData$PhysActivity)
table(summaryDiabetesData$Sex)
table(summaryDiabetesData$DiffWalk)

# Boxplot
f <- ggplot(newDiabetesData, aes(x = Diabetes_binary, y = BMI))
f + geom_boxplot() +
  labs(title = "Boxplot of Value by Category", x = "Category", y = "Value")

contingency_table <- table(newDiabetesData$Diabetes_binary, newDiabetesData$PhysActivity)

heatmap_data <- as.data.frame(as.table(contingency_table))

# Heatmap
g <- ggplot(heatmap_data, aes(x = Var1, y = Var2, fill = Freq))
g + geom_tile() +
  scale_fill_gradient(low = "white", high = "blue") +
  labs(title = "Heatmap of Cat1 by Cat2", x = "Category 1", y = "Category 2")


```

[Click here for the Modeling Page](Modeling.html)
