---
title: "Modeling File"
author: "Eliza Norman"
format: html
editor: visual
---

# Modeling File

```{r}
#| warning: FALSE
library(tidyverse)
library(reshape2)
library(caret)

```

```{r}

#| echo: FALSE
diabetesData <- read_csv("diabetes_binary_health_indicators_BRFSS2015.csv", show_col_types = FALSE)

diabetesData$Diabetes_binary <- factor(diabetesData$Diabetes_binary,
         levels = c(0,1),
         labels = c("No diabetes", "Diabetes"))

diabetesData$HighChol <- factor(diabetesData$HighChol,
         levels = c(0,1),
         labels = c("No high cholesterol", "High cholesterol"))

diabetesData$Smoker <- factor(diabetesData$Smoker,
         levels = c(0,1),
         labels = c("Never smoked at least 100 cigs", "Has smoked at least 100 cigs"))

diabetesData$PhysActivity <- factor(diabetesData$PhysActivity,
         levels = c(0,1),
         labels = c("No physical activity", "Physical activity"))

diabetesData$Sex <- factor(diabetesData$Sex,
         levels = c(0,1),
         labels = c("Female", "Male"))

diabetesData$Age <- factor(diabetesData$Age,
         levels = c(1,2,3,4,5,6,7,8,9,10,11,12,13),
         labels = c("20-24","25-29", "30-34", "35-39", "40-44", "45-49","51-54","55-59","60-64", "65-69", "70-74", "75-79", "80 or older"))

diabetesData$HvyAlcoholConsump <- factor(diabetesData$HvyAlcoholConsump,
         levels = c(0,1),
         labels = c("No", "Yes"))

diabetesData$DiffWalk <- factor(diabetesData$DiffWalk,
         levels = c(0,1),
         labels = c("No serious difficulty walking up stairs", "Serious difficulty walking stairs"))

newDiabetesData <- diabetesData |>
  select(Diabetes_binary, HighChol, BMI, Smoker, PhysActivity, HvyAlcoholConsump, Sex, Age, DiffWalk)

```

```{r}
set.seed(50)

index <- createDataPartition(newDiabetesData$Diabetes_binary, p = 0.7, list = FALSE)
trainData <- newDiabetesData[index, ]
testData <- newDiabetesData[-index, ]
```

```{r}
#| echo: false
2 * 2
```

The `echo: false` option disables the printing of code (only output is displayed).
